Repository YeoGiDa/YeoGiDa-Backend, pull requests merged in 2022-12, with the labels that each got.

#15 [CHORE] initDB 세팅
  src/main/java/com/Udemy/YeoGiDa/InitDb.java
  src/main/java/com/Udemy/YeoGiDa/domain/heart/controller/HeartController.java
  src/main/java/com/Udemy/YeoGiDa/domain/heart/response/HeartDto.java
  src/main/java/com/Udemy/YeoGiDa/domain/heart/service/HeartService.java
Labels: ⚙ Setting, 형래

#16 [FEAT] Heart 좋아요 관련 기능 및 API 개발
  src/main/java/com/Udemy/YeoGiDa/domain/heart/entity/Heart.java
  src/main/java/com/Udemy/YeoGiDa/domain/heart/exception/AlreadyHeartException.java
  src/main/java/com/Udemy/YeoGiDa/domain/heart/exception/HeartNotFoundException.java
  src/main/java/com/Udemy/YeoGiDa/domain/heart/repository/HeartRepository.java
  src/main/java/com/Udemy/YeoGiDa/domain/trip/entity/Trip.java
  src/main/java/com/Udemy/YeoGiDa/domain/trip/repository/TripRepositoryCustom.java
  src/main/java/com/Udemy/YeoGiDa/domain/trip/repository/TripRepositoryImpl.java
  src/main/java/com/Udemy/YeoGiDa/domain/trip/response/TripListResponseDto.java
  src/main/java/com/Udemy/YeoGiDa/domain/trip/service/TripService.java
Labels: ✨ Feature, 📬 API, 형래

#17 [FIX] Jwt 토큰 로직 수정, Error Response 템플릿 변경
  src/main/java/com/Udemy/YeoGiDa/domain/member/controller/MemberController.java
  src/main/java/com/Udemy/YeoGiDa/domain/member/service/MemberService.java
  src/main/java/com/Udemy/YeoGiDa/domain/trip/controller/TripController.java
  src/main/java/com/Udemy/YeoGiDa/global/error/GlobalExceptionHandler.java
  src/main/java/com/Udemy/YeoGiDa/global/error/dto/ErrorResult.java
  src/main/java/com/Udemy/YeoGiDa/global/jwt/Token.java
  src/main/java/com/Udemy/YeoGiDa/global/jwt/controller/TokenController.java
  src/main/java/com/Udemy/YeoGiDa/global/jwt/filter/JwtAuthenticationFilter.java
  src/main/java/com/Udemy/YeoGiDa/global/jwt/service/JwtProvider.java
Labels: 🐞 BugFix, 📬 API, 형래

#19 [FIX] member API response 수정
  src/main/java/com/Udemy/YeoGiDa/domain/member/controller/MemberController.java
  src/main/java/com/Udemy/YeoGiDa/domain/member/service/MemberService.java
Labels: 🐞 BugFix, 📬 API, 형래

#20 [CHORE] Swagger 수정 및 재설정
  src/main/java/com/Udemy/YeoGiDa/domain/member/controller/MemberController.java
  src/main/java/com/Udemy/YeoGiDa/domain/member/request/MemberJoinRequest.java
  src/main/java/com/Udemy/YeoGiDa/domain/member/request/MemberLoginRequest.java
  src/main/java/com/Udemy/YeoGiDa/domain/member/request/MemberUpdateRequest.java
  src/main/java/com/Udemy/YeoGiDa/domain/trip/controller/TripController.java
  src/main/java/com/Udemy/YeoGiDa/global/config/SwaggerConfig.java
  src/main/java/com/Udemy/YeoGiDa/global/jwt/controller/TokenController.java
  src/main/java/com/Udemy/YeoGiDa/global/jwt/filter/JwtAuthenticationFilter.java
Labels: ⚙ Setting, 📬 API, 형래

#27 [FEAT] Amazon S3 연동
  .gitignore
  build.gradle
  build/tmp/compileJava/previous-compilation-data.bin
  settings.gradle
  src/main/java/com/Udemy/YeoGiDa/InitDb.java
  src/main/java/com/Udemy/YeoGiDa/domain/common/exception/ImgNotFoundException.java
  src/main/java/com/Udemy/YeoGiDa/domain/common/exception/WrongImgFormatException.java
  src/main/java/com/Udemy/YeoGiDa/domain/common/service/S3Service.java
  src/main/java/com/Udemy/YeoGiDa/domain/member/controller/MemberController.java
  src/main/java/com/Udemy/YeoGiDa/domain/member/entity/Member.java
  src/main/java/com/Udemy/YeoGiDa/domain/member/entity/MemberImg.java
  src/main/java/com/Udemy/YeoGiDa/domain/member/repository/MemberImgRepository.java
  src/main/java/com/Udemy/YeoGiDa/domain/member/request/MemberJoinRequest.java
  src/main/java/com/Udemy/YeoGiDa/domain/member/request/MemberUpdateRequest.java
  src/main/java/com/Udemy/YeoGiDa/domain/member/response/MemberDto.java
  src/main/java/com/Udemy/YeoGiDa/domain/member/service/MemberService.java
  src/main/java/com/Udemy/YeoGiDa/domain/place/controller/PlaceController.java
  src/main/java/com/Udemy/YeoGiDa/domain/place/entity/Place.java
  src/main/java/com/Udemy/YeoGiDa/domain/place/entity/PlaceImg.java
  src/main/java/com/Udemy/YeoGiDa/domain/place/repository/PlaceImgRepository.java
  src/main/java/com/Udemy/YeoGiDa/domain/place/response/PlaceDetailResponseDto.java
  src/main/java/com/Udemy/YeoGiDa/domain/place/response/PlaceListResponseDto.java
  src/main/java/com/Udemy/YeoGiDa/domain/place/service/PlaceService.java
  src/main/java/com/Udemy/YeoGiDa/domain/trip/controller/TripController.java
  src/main/java/com/Udemy/YeoGiDa/domain/trip/entity/Trip.java
  src/main/java/com/Udemy/YeoGiDa/domain/trip/entity/TripImg.java
  src/main/java/com/Udemy/YeoGiDa/domain/trip/repository/TripImgRepository.java
  src/main/java/com/Udemy/YeoGiDa/domain/trip/response/TripDetailResponseDto.java
  src/main/java/com/Udemy/YeoGiDa/domain/trip/response/TripListResponseDto.java
  src/main/java/com/Udemy/YeoGiDa/domain/trip/service/TripService.java
  src/main/resources/application.yml
Labels: ⚙ Setting, ✨ Feature, 📬 API, 형래

#30 [FIX] amazon s3 rds 삭제 오류 수정
  .gitignore
  src/main/java/com/Udemy/YeoGiDa/domain/common/service/S3Service.java
  src/main/java/com/Udemy/YeoGiDa/domain/member/controller/MemberController.java
  src/main/java/com/Udemy/YeoGiDa/domain/member/service/MemberService.java
  src/main/java/com/Udemy/YeoGiDa/domain/trip/controller/TripController.java
  src/main/java/com/Udemy/YeoGiDa/domain/trip/repository/TripRepository.java
  src/main/java/com/Udemy/YeoGiDa/domain/trip/repository/TripRepositoryCustom.java
  src/main/java/com/Udemy/YeoGiDa/domain/trip/repository/TripRepositoryImpl.java
  src/main/java/com/Udemy/YeoGiDa/domain/trip/service/TripService.java
Labels: 🐞 BugFix, 📬 API, 형래

#31 [FIX] DB에 없는 회원 accessToken 접근 제한
  src/main/java/com/Udemy/YeoGiDa/global/jwt/service/JwtProvider.java
Labels: 🐞 BugFix, 형래

#34 [FIX] 장소 Place 위도 경도 Double Type 변경
  src/main/java/com/Udemy/YeoGiDa/domain/place/entity/Place.java
  src/main/java/com/Udemy/YeoGiDa/domain/place/request/PlaceSaveRequestDto.java
  src/main/java/com/Udemy/YeoGiDa/domain/place/request/PlaceUpdateRequestDto.java
  src/main/java/com/Udemy/YeoGiDa/domain/place/service/PlaceService.java
Labels: 🐞 BugFix, 상윤

#35 [FEAT] 엔티티와 S3 이미지 연동 개발
  src/main/java/com/Udemy/YeoGiDa/InitDb.java
  src/main/java/com/Udemy/YeoGiDa/domain/member/controller/MemberController.java
  src/main/java/com/Udemy/YeoGiDa/domain/member/service/MemberService.java
  src/main/java/com/Udemy/YeoGiDa/domain/place/controller/PlaceController.java
  src/main/java/com/Udemy/YeoGiDa/domain/place/entity/Place.java
  src/main/java/com/Udemy/YeoGiDa/domain/place/response/PlaceDetailResponseDto.java
  src/main/java/com/Udemy/YeoGiDa/domain/place/response/PlaceListResponseDto.java
  src/main/java/com/Udemy/YeoGiDa/domain/place/service/PlaceService.java
Labels: ✨ Feature, 📬 API, 형래

#37 [FEAT] #33 댓글 Comment 삭제 API 수정
  src/main/java/com/Udemy/YeoGiDa/domain/comment/service/CommentService.java
Labels: ✨ Feature, 📬 API, 상윤

#39 [FEAT] 장소 API 개발
  src/main/java/com/Udemy/YeoGiDa/InitDb.java
  src/main/java/com/Udemy/YeoGiDa/domain/place/controller/PlaceController.java
  src/main/java/com/Udemy/YeoGiDa/domain/place/entity/Place.java
  src/main/java/com/Udemy/YeoGiDa/domain/place/repository/PlaceRepositoryCustom.java
  src/main/java/com/Udemy/YeoGiDa/domain/place/repository/PlaceRepositoryImpl.java
  src/main/java/com/Udemy/YeoGiDa/domain/place/request/PlaceUpdateRequestDto.java
  src/main/java/com/Udemy/YeoGiDa/domain/place/response/PlaceListResponseDto.java
  src/main/java/com/Udemy/YeoGiDa/domain/place/service/PlaceService.java
Labels: ✨ Feature, 🐞 BugFix, 📬 API, 상윤

#43 [FIX] rest api response 형식 수정
  .gitignore
  src/main/java/com/Udemy/YeoGiDa/InitDb.java
  src/main/java/com/Udemy/YeoGiDa/domain/member/controller/MemberController.java
  src/main/java/com/Udemy/YeoGiDa/domain/place/controller/PlaceController.java
  src/main/java/com/Udemy/YeoGiDa/domain/trip/controller/TripController.java
  src/main/resources/application-dev.yml
  src/main/resources/application-prod.yml
  src/main/resources/application.properties
  src/main/resources/application.yml
Labels: ⚙ Setting, 🐞 BugFix, 📬 API, 형래

#44 [FEAT] Follow API 기능 개발
  src/main/java/com/Udemy/YeoGiDa/domain/follow/controller/FollowController.java
  src/main/java/com/Udemy/YeoGiDa/domain/follow/entity/Follow.java
  src/main/java/com/Udemy/YeoGiDa/domain/follow/exception/AlreadyFollowException.java
  src/main/java/com/Udemy/YeoGiDa/domain/follow/exception/FollowNotFoundException.java
  src/main/java/com/Udemy/YeoGiDa/domain/follow/repository/FollowRepository.java
  src/main/java/com/Udemy/YeoGiDa/domain/follow/repository/FollowRepositoryCustom.java
  src/main/java/com/Udemy/YeoGiDa/domain/follow/repository/FollowRepositoryImpl.java
  src/main/java/com/Udemy/YeoGiDa/domain/follow/response/FollowResponseDto.java
  src/main/java/com/Udemy/YeoGiDa/domain/follow/service/FollowService.java
  src/main/java/com/Udemy/YeoGiDa/domain/place/request/PlaceSaveRequestDto.java
  src/main/java/com/Udemy/YeoGiDa/domain/place/service/PlaceService.java
Labels: ✨ Feature, 📬 API, 상윤

#50 [FIX] 400, 500대 error handling
  src/main/java/com/Udemy/YeoGiDa/domain/trip/controller/TripController.java
  src/main/java/com/Udemy/YeoGiDa/domain/trip/service/TripService.java
  src/main/java/com/Udemy/YeoGiDa/global/error/GlobalExceptionHandler.java
  src/main/java/com/Udemy/YeoGiDa/global/jwt/controller/TokenController.java
  src/main/java/com/Udemy/YeoGiDa/global/jwt/exception/TokenHasExpiredException.java
  src/main/java/com/Udemy/YeoGiDa/global/jwt/filter/JwtAuthenticationFilter.java
  src/main/java/com/Udemy/YeoGiDa/global/jwt/service/JwtProvider.java
Labels: 🐞 BugFix, 형래

#51 [FIX] 장소 Place 댓글 갯수 CommentCount 기능 추가
  src/main/java/com/Udemy/YeoGiDa/domain/place/controller/PlaceController.java
  src/main/java/com/Udemy/YeoGiDa/domain/place/entity/Place.java
  src/main/java/com/Udemy/YeoGiDa/domain/place/repository/PlaceRepositoryCustom.java
  src/main/java/com/Udemy/YeoGiDa/domain/place/repository/PlaceRepositoryImpl.java
  src/main/java/com/Udemy/YeoGiDa/domain/place/response/PlaceListResponseDto.java
  src/main/java/com/Udemy/YeoGiDa/domain/place/service/PlaceService.java
  src/main/resources/application.yml
Labels: ✨ Feature, 🐞 BugFix, 상윤

#53 [FIX] 여행지 Trip API 개선
  src/main/java/com/Udemy/YeoGiDa/InitDb.java
  src/main/java/com/Udemy/YeoGiDa/domain/trip/controller/TripController.java
  src/main/java/com/Udemy/YeoGiDa/domain/trip/entity/Trip.java
  src/main/java/com/Udemy/YeoGiDa/domain/trip/repository/TripRepositoryCustom.java
  src/main/java/com/Udemy/YeoGiDa/domain/trip/repository/TripRepositoryImpl.java
  src/main/java/com/Udemy/YeoGiDa/domain/trip/response/TripListResponseDto.java
  src/main/java/com/Udemy/YeoGiDa/domain/trip/service/TripService.java
Labels: 🐞 BugFix, 상윤

#55 [FIX] 장소 Place, 댓글 Comment API 수정
  src/main/java/com/Udemy/YeoGiDa/domain/comment/response/CommentListResponseDto.java
  src/main/java/com/Udemy/YeoGiDa/domain/place/controller/PlaceController.java
  src/main/java/com/Udemy/YeoGiDa/domain/place/repository/PlaceRepositoryCustom.java
  src/main/java/com/Udemy/YeoGiDa/domain/place/repository/PlaceRepositoryImpl.java
  src/main/java/com/Udemy/YeoGiDa/domain/place/response/PlaceDetailResponseDto.java
  src/main/java/com/Udemy/YeoGiDa/domain/place/response/PlaceListResponseDto.java
  src/main/java/com/Udemy/YeoGiDa/domain/place/service/PlaceService.java
Labels: 🐞 BugFix, 📬 API, 상윤

#57 [FEAT] 장소 Place API 개선
  src/main/java/com/Udemy/YeoGiDa/domain/comment/controller/CommentController.java
  src/main/java/com/Udemy/YeoGiDa/domain/comment/entity/Comment.java
  src/main/java/com/Udemy/YeoGiDa/domain/comment/exception/CommentNotFoundException.java
  src/main/java/com/Udemy/YeoGiDa/domain/comment/response/CommentListResponseDto.java
  src/main/java/com/Udemy/YeoGiDa/domain/member/controller/MemberController.java
  src/main/java/com/Udemy/YeoGiDa/domain/member/response/MemberLoginResponse.java
  src/main/java/com/Udemy/YeoGiDa/domain/member/service/MemberService.java
  src/main/java/com/Udemy/YeoGiDa/domain/place/controller/PlaceController.java
  src/main/java/com/Udemy/YeoGiDa/domain/place/repository/PlaceRepositoryCustom.java
  src/main/java/com/Udemy/YeoGiDa/domain/place/repository/PlaceRepositoryImpl.java
  src/main/java/com/Udemy/YeoGiDa/domain/place/service/PlaceService.java
Labels: ✨ Feature, 📬 API, 상윤

#62 [FIX] 장소 Place API의 Star ㅇ
  src/main/java/com/Udemy/YeoGiDa/domain/place/entity/Place.java
  src/main/java/com/Udemy/YeoGiDa/domain/place/request/PlaceSaveRequestDto.java
  src/main/java/com/Udemy/YeoGiDa/domain/place/request/PlaceUpdateRequestDto.java
  src/main/java/com/Udemy/YeoGiDa/domain/place/response/PlaceDetailResponseDto.java
  src/main/java/com/Udemy/YeoGiDa/domain/place/response/PlaceListResponseDto.java
  src/main/java/com/Udemy/YeoGiDa/domain/trip/repository/TripRepository.java
  src/main/java/com/Udemy/YeoGiDa/domain/trip/repository/TripRepositoryCustom.java
  src/main/java/com/Udemy/YeoGiDa/domain/trip/service/TripService.java
  src/main/resources/application.yml
Labels: 🐞 BugFix

#63 [FIX] 장소 Place Data type 수정
  src/main/java/com/Udemy/YeoGiDa/InitDb.java
Labels: 🐞 BugFix, 상윤

#65 [FIX] API 수정
  src/main/java/com/Udemy/YeoGiDa/InitDb.java
  src/main/java/com/Udemy/YeoGiDa/domain/member/entity/Member.java
  src/main/java/com/Udemy/YeoGiDa/domain/place/controller/PlaceController.java
  src/main/java/com/Udemy/YeoGiDa/domain/place/response/PlaceListResponseDto.java
  src/main/java/com/Udemy/YeoGiDa/domain/trip/controller/TripController.java
  src/main/java/com/Udemy/YeoGiDa/domain/trip/service/TripService.java
Labels: ⚙ Setting, 🐞 BugFix, 형래

#67 [FEAT] 장소 Place 리스트의 여행지 정보 API 개발
  src/main/java/com/Udemy/YeoGiDa/domain/place/controller/PlaceController.java
  src/main/java/com/Udemy/YeoGiDa/domain/place/response/PlaceListInTripResponseDto.java
  src/main/java/com/Udemy/YeoGiDa/domain/place/service/PlaceService.java
Labels: enhancement, 📬 API, 상윤

#70 [FIX] 장소 Place 장소 조회 리스트 URL 수정
  src/main/java/com/Udemy/YeoGiDa/domain/place/controller/PlaceController.java
  src/main/java/com/Udemy/YeoGiDa/domain/place/repository/PlaceRepositoryCustom.java
  src/main/java/com/Udemy/YeoGiDa/domain/place/repository/PlaceRepositoryImpl.java
  src/main/java/com/Udemy/YeoGiDa/domain/place/service/PlaceService.java
Labels: enhancement, 📬 API, 상윤

#72 [FEAT] 댓글 Comment 무한 스크롤(Cursor Paging) 개발
  src/main/java/com/Udemy/YeoGiDa/domain/comment/controller/CommentController.java
  src/main/java/com/Udemy/YeoGiDa/domain/comment/entity/Comment.java
  src/main/java/com/Udemy/YeoGiDa/domain/comment/repository/CommentRepository.java
  src/main/java/com/Udemy/YeoGiDa/domain/comment/repository/CommentRepositoryCustom.java
  src/main/java/com/Udemy/YeoGiDa/domain/comment/repository/CommentRepositoryImpl.java
  src/main/java/com/Udemy/YeoGiDa/domain/comment/response/CommentListResponseDto.java
  src/main/java/com/Udemy/YeoGiDa/domain/comment/service/CommentService.java
  src/main/java/com/Udemy/YeoGiDa/domain/place/controller/PlaceController.java
  src/main/java/com/Udemy/YeoGiDa/domain/place/response/PlaceListInTripResponseDto.java
  src/main/java/com/Udemy/YeoGiDa/domain/place/service/PlaceService.java
Labels: ✨ Feature, 📬 API, 상윤

#74 [FEAT] 장소 Place 내가 댓글 단 장소 API 개발
  src/main/java/com/Udemy/YeoGiDa/domain/place/controller/PlaceController.java
  src/main/java/com/Udemy/YeoGiDa/domain/place/repository/PlaceRepositoryCustom.java
  src/main/java/com/Udemy/YeoGiDa/domain/place/repository/PlaceRepositoryImpl.java
  src/main/java/com/Udemy/YeoGiDa/domain/place/service/PlaceService.java
Labels: ✨ Feature, 📬 API, 상윤

#75 [FEAT] 알람 API 개발
  .gitignore
  build.gradle
  src/main/java/com/Udemy/YeoGiDa/domain/alarm/controller/AlarmController.java
  src/main/java/com/Udemy/YeoGiDa/domain/alarm/entity/Alarm.java
  src/main/java/com/Udemy/YeoGiDa/domain/alarm/entity/AlarmType.java
  src/main/java/com/Udemy/YeoGiDa/domain/alarm/exception/AlarmNotFoundException.java
  src/main/java/com/Udemy/YeoGiDa/domain/alarm/repository/AlarmRepository.java
  src/main/java/com/Udemy/YeoGiDa/domain/alarm/repository/AlarmRepositoryCustom.java
  src/main/java/com/Udemy/YeoGiDa/domain/alarm/repository/AlarmRepositoryImpl.java
  src/main/java/com/Udemy/YeoGiDa/domain/alarm/response/AlarmListResponseDto.java
  src/main/java/com/Udemy/YeoGiDa/domain/alarm/service/AlarmService.java
  src/main/java/com/Udemy/YeoGiDa/domain/comment/entity/Comment.java
  src/main/java/com/Udemy/YeoGiDa/domain/comment/response/CommentListResponseDto.java
  src/main/java/com/Udemy/YeoGiDa/domain/comment/service/CommentService.java
  src/main/java/com/Udemy/YeoGiDa/domain/follow/controller/FollowController.java
  src/main/java/com/Udemy/YeoGiDa/domain/follow/response/FollowResponseDto.java
  src/main/java/com/Udemy/YeoGiDa/domain/follow/service/FollowService.java
  src/main/java/com/Udemy/YeoGiDa/domain/trip/controller/TripController.java
  src/main/java/com/Udemy/YeoGiDa/domain/trip/service/TripService.java
  src/main/resources/application-prod.yml
  src/main/resources/application.yml
Labels: ✨ Feature, 📬 API, 형래

#78 [FEAT] 팔로우 Follow 검색 API 개발
  src/main/java/com/Udemy/YeoGiDa/domain/follow/controller/FollowController.java
  src/main/java/com/Udemy/YeoGiDa/domain/follow/repository/FollowRepository.java
  src/main/java/com/Udemy/YeoGiDa/domain/follow/repository/FollowRepositoryCustom.java
  src/main/java/com/Udemy/YeoGiDa/domain/follow/repository/FollowRepositoryImpl.java
  src/main/java/com/Udemy/YeoGiDa/domain/follow/service/FollowService.java
Labels: ✨ Feature, 📬 API, 상윤

#80 [FIX] 장소 Place 반환 타입 수정
  src/main/java/com/Udemy/YeoGiDa/domain/place/entity/PlaceImg.java
  src/main/java/com/Udemy/YeoGiDa/domain/place/response/PlaceDetailResponseDto.java
Labels: 🐞 BugFix, 📬 API, 상윤

#82 [FIX] 팔로우 Follow 검색 API 수정
  src/main/java/com/Udemy/YeoGiDa/InitDb.java
  src/main/java/com/Udemy/YeoGiDa/domain/comment/service/CommentService.java
  src/main/java/com/Udemy/YeoGiDa/domain/follow/controller/FollowController.java
  src/main/java/com/Udemy/YeoGiDa/domain/follow/service/FollowService.java
Labels: 🐞 BugFix, 📬 API, 상윤

#83 [FEAT] 베스트 여행지, 친구가 작성한 여행지 API
  src/main/java/com/Udemy/YeoGiDa/InitDb.java
  src/main/java/com/Udemy/YeoGiDa/domain/comment/service/CommentService.java
  src/main/java/com/Udemy/YeoGiDa/domain/follow/repository/FollowRepositoryCustom.java
  src/main/java/com/Udemy/YeoGiDa/domain/follow/repository/FollowRepositoryImpl.java
  src/main/java/com/Udemy/YeoGiDa/domain/follow/service/FollowService.java
  src/main/java/com/Udemy/YeoGiDa/domain/heart/repository/HeartRepository.java
  src/main/java/com/Udemy/YeoGiDa/domain/heart/repository/HeartRepositoryCustom.java
  src/main/java/com/Udemy/YeoGiDa/domain/heart/repository/HeartRepositoryImpl.java
  src/main/java/com/Udemy/YeoGiDa/domain/member/controller/MemberController.java
  src/main/java/com/Udemy/YeoGiDa/domain/member/entity/Member.java
  src/main/java/com/Udemy/YeoGiDa/domain/member/repository/MemberRepositoryImpl.java
  src/main/java/com/Udemy/YeoGiDa/domain/member/response/BestTravlerListResponse.java
  src/main/java/com/Udemy/YeoGiDa/domain/member/service/MemberService.java
  src/main/java/com/Udemy/YeoGiDa/domain/trip/controller/TripController.java
  src/main/java/com/Udemy/YeoGiDa/domain/trip/exception/HeartTripNotFoundException.java
  src/main/java/com/Udemy/YeoGiDa/domain/trip/exception/TripNotFoundException.java
  src/main/java/com/Udemy/YeoGiDa/domain/trip/repository/TripRepositoryCustom.java
  src/main/java/com/Udemy/YeoGiDa/domain/trip/repository/TripRepositoryImpl.java
  src/main/java/com/Udemy/YeoGiDa/domain/trip/service/TripService.java
Labels: ✨ Feature, 📬 API, 형래

#86 [FEAT] 여행지 Trip 검색 API 개발
  src/main/java/com/Udemy/YeoGiDa/domain/trip/controller/TripController.java
  src/main/java/com/Udemy/YeoGiDa/domain/trip/service/TripService.java
  src/main/resources/application.yml
Labels: ✨ Feature, 📬 API, 상윤

#89 [FEAT] 장소 Place 지도 위의 장소 조회 API 개발
  src/main/java/com/Udemy/YeoGiDa/domain/place/controller/PlaceController.java
  src/main/java/com/Udemy/YeoGiDa/domain/place/response/PlaceDetailResponseDto.java
  src/main/java/com/Udemy/YeoGiDa/domain/place/response/PlaceListInMapResponseDto.java
  src/main/java/com/Udemy/YeoGiDa/domain/place/service/PlaceService.java
Labels: ✨ Feature, 📬 API, 상윤

#91 [FEAT] 팔로잉이 작성한 최근 여행지 API 개발
  src/main/java/com/Udemy/YeoGiDa/InitDb.java
  src/main/java/com/Udemy/YeoGiDa/domain/follow/exception/FollowNotFoundException.java
  src/main/java/com/Udemy/YeoGiDa/domain/follow/exception/NoOneFollowException.java
  src/main/java/com/Udemy/YeoGiDa/domain/follow/repository/FollowRepositoryCustom.java
  src/main/java/com/Udemy/YeoGiDa/domain/follow/repository/FollowRepositoryImpl.java
  src/main/java/com/Udemy/YeoGiDa/domain/trip/controller/TripController.java
  src/main/java/com/Udemy/YeoGiDa/domain/trip/repository/TripRepository.java
  src/main/java/com/Udemy/YeoGiDa/domain/trip/repository/TripRepositoryCustom.java
  src/main/java/com/Udemy/YeoGiDa/domain/trip/response/TripListResponseDto.java
  src/main/java/com/Udemy/YeoGiDa/domain/trip/service/TripService.java
  src/main/java/com/Udemy/YeoGiDa/global/error/GlobalExceptionHandler.java
Labels: ✨ Feature, 📬 API, 형래

#93 [FEAT] 팔로우 Follow 유저상세, 장소 Place API 개선
  src/main/java/com/Udemy/YeoGiDa/InitDb.java
  src/main/java/com/Udemy/YeoGiDa/domain/follow/controller/FollowController.java
  src/main/java/com/Udemy/YeoGiDa/domain/follow/repository/FollowRepositoryCustom.java
  src/main/java/com/Udemy/YeoGiDa/domain/follow/repository/FollowRepositoryImpl.java
  src/main/java/com/Udemy/YeoGiDa/domain/follow/response/FollowMemberDetailResponseDto.java
  src/main/java/com/Udemy/YeoGiDa/domain/follow/service/FollowService.java
  src/main/java/com/Udemy/YeoGiDa/domain/member/controller/MemberController.java
  src/main/java/com/Udemy/YeoGiDa/domain/member/response/MemberDetailResponseDto.java
  src/main/java/com/Udemy/YeoGiDa/domain/member/service/MemberService.java
  src/main/java/com/Udemy/YeoGiDa/domain/place/controller/PlaceController.java
  src/main/java/com/Udemy/YeoGiDa/domain/place/repository/PlaceRepositoryCustom.java
  src/main/java/com/Udemy/YeoGiDa/domain/place/repository/PlaceRepositoryImpl.java
  src/main/java/com/Udemy/YeoGiDa/domain/place/service/PlaceService.java
  src/main/java/com/Udemy/YeoGiDa/domain/trip/repository/TripRepositoryCustom.java
  src/main/java/com/Udemy/YeoGiDa/domain/trip/repository/TripRepositoryImpl.java
Labels: ✨ Feature, 📬 API, 상윤

#95 [FEAT] 팔로우 Follow 목록 조회 및 상세페이지 기능 구현
  src/main/java/com/Udemy/YeoGiDa/domain/follow/controller/FollowController.java
  src/main/java/com/Udemy/YeoGiDa/domain/place/repository/PlaceRepositoryImpl.java
  src/main/java/com/Udemy/YeoGiDa/domain/trip/controller/TripController.java
  src/main/java/com/Udemy/YeoGiDa/domain/trip/repository/TripRepository.java
  src/main/java/com/Udemy/YeoGiDa/domain/trip/repository/TripRepositoryCustom.java
  src/main/java/com/Udemy/YeoGiDa/domain/trip/repository/TripRepositoryImpl.java
  src/main/java/com/Udemy/YeoGiDa/domain/trip/service/TripService.java
Labels: ✨ Feature, 📬 API, 상윤

#96 [FEAT] 알림 API와 FCM 푸시알림 연동
  .gitignore
  build.gradle
  src/main/java/com/Udemy/YeoGiDa/InitDb.java
  src/main/java/com/Udemy/YeoGiDa/domain/alarm/repository/AlarmRepositoryCustom.java
  src/main/java/com/Udemy/YeoGiDa/domain/alarm/repository/AlarmRepositoryImpl.java
  src/main/java/com/Udemy/YeoGiDa/domain/comment/controller/CommentController.java
  src/main/java/com/Udemy/YeoGiDa/domain/comment/service/CommentService.java
  src/main/java/com/Udemy/YeoGiDa/domain/follow/controller/FollowController.java
  src/main/java/com/Udemy/YeoGiDa/domain/follow/service/FollowService.java
  src/main/java/com/Udemy/YeoGiDa/domain/member/entity/Member.java
  src/main/java/com/Udemy/YeoGiDa/domain/member/request/MemberJoinRequest.java
  src/main/java/com/Udemy/YeoGiDa/domain/member/request/MemberLoginRequest.java
  src/main/java/com/Udemy/YeoGiDa/domain/member/request/MemberUpdateRequest.java
  src/main/java/com/Udemy/YeoGiDa/domain/member/service/MemberService.java
  src/main/java/com/Udemy/YeoGiDa/domain/trip/controller/TripController.java
  src/main/java/com/Udemy/YeoGiDa/domain/trip/service/TripService.java
  src/main/java/com/Udemy/YeoGiDa/global/fcm/controller/FcmController.java
  src/main/java/com/Udemy/YeoGiDa/global/fcm/dto/FcmMessage.java
  src/main/java/com/Udemy/YeoGiDa/global/fcm/dto/RequestDto.java
  src/main/java/com/Udemy/YeoGiDa/global/fcm/service/FirebaseCloudMessageService.java
Labels: ⚙ Setting, ✨ Feature, 📬 API, 형래

#99 [FIX] 팔로우 Follow 유저 상세페이지 수정
  src/main/java/com/Udemy/YeoGiDa/domain/follow/response/FollowMemberDetailResponseDto.java
Labels: 🐞 BugFix, 상윤

#100 [FIX] 알림 API 수정
  src/main/java/com/Udemy/YeoGiDa/domain/comment/service/CommentService.java
  src/main/java/com/Udemy/YeoGiDa/domain/follow/service/FollowService.java
  src/main/java/com/Udemy/YeoGiDa/domain/trip/service/TripService.java
  src/main/java/com/Udemy/YeoGiDa/global/fcm/controller/FcmController.java
  src/main/java/com/Udemy/YeoGiDa/global/fcm/dto/FcmMessage.java
  src/main/java/com/Udemy/YeoGiDa/global/fcm/dto/RequestDto.java
  src/main/java/com/Udemy/YeoGiDa/global/fcm/service/FirebaseCloudMessageService.java
Labels: 🐞 BugFix, 형래

#103 [FEAT] 여행지, 장소 Trip,Place API 멘토링 내용 반영
  src/main/java/com/Udemy/YeoGiDa/domain/alarm/controller/AlarmController.java
  src/main/java/com/Udemy/YeoGiDa/domain/alarm/entity/Alarm.java
  src/main/java/com/Udemy/YeoGiDa/domain/alarm/repository/AlarmRepositoryImpl.java
  src/main/java/com/Udemy/YeoGiDa/domain/comment/repository/CommentRepositoryImpl.java
  src/main/java/com/Udemy/YeoGiDa/domain/place/controller/PlaceController.java
  src/main/java/com/Udemy/YeoGiDa/domain/place/entity/Place.java
  src/main/java/com/Udemy/YeoGiDa/domain/place/repository/PlaceRepositoryCustom.java
  src/main/java/com/Udemy/YeoGiDa/domain/place/repository/PlaceRepositoryImpl.java
  src/main/java/com/Udemy/YeoGiDa/domain/place/service/PlaceService.java
  src/main/java/com/Udemy/YeoGiDa/domain/trip/entity/TripImg.java
  src/main/java/com/Udemy/YeoGiDa/domain/trip/repository/TripRepository.java
  src/main/java/com/Udemy/YeoGiDa/domain/trip/repository/TripRepositoryImpl.java
  src/main/java/com/Udemy/YeoGiDa/domain/trip/response/TripListResponseDto.java
  src/main/java/com/Udemy/YeoGiDa/domain/trip/service/TripService.java
  src/main/java/com/Udemy/YeoGiDa/global/fcm/service/FirebaseCloudMessageService.java
Labels: 📬 API, 🔨 Refactor, 상윤

#104 [FIX] 장소 리스트의 여행지 정보 Response 수정
  src/main/java/com/Udemy/YeoGiDa/domain/place/controller/PlaceController.java
Labels: 🐞 BugFix, 상윤

#106 [FIX] 장소 리스트의 여행지 정보 Response 재수정
  src/main/java/com/Udemy/YeoGiDa/domain/place/controller/PlaceController.java
  src/main/java/com/Udemy/YeoGiDa/domain/place/response/PlaceListInTripResponseDto.java
Labels: 🐞 BugFix, 상윤

#109 [FIX] 장소 리스트의 여행지 정보 Response 재수정
  src/main/java/com/Udemy/YeoGiDa/domain/follow/controller/FollowController.java
  src/main/java/com/Udemy/YeoGiDa/domain/follow/response/FollowResponseDto.java
  src/main/java/com/Udemy/YeoGiDa/domain/follow/service/FollowService.java
  src/main/java/com/Udemy/YeoGiDa/domain/heart/repository/HeartRepository.java
  src/main/java/com/Udemy/YeoGiDa/domain/place/controller/PlaceController.java
  src/main/java/com/Udemy/YeoGiDa/domain/place/response/PlaceListInTripResponseDto.java
  src/main/java/com/Udemy/YeoGiDa/domain/place/service/PlaceService.java
Labels: 🐞 BugFix, 상윤

#110 [FEAT] 장소 둘러보기 API 개발
  src/main/java/com/Udemy/YeoGiDa/InitDb.java
  src/main/java/com/Udemy/YeoGiDa/domain/place/controller/PlaceController.java
  src/main/java/com/Udemy/YeoGiDa/domain/place/repository/PlaceRepository.java
  src/main/java/com/Udemy/YeoGiDa/domain/place/response/PlaceAroundMarkerResponseDto.java
  src/main/java/com/Udemy/YeoGiDa/domain/place/response/PlaceAroundViewResponseDto.java
  src/main/java/com/Udemy/YeoGiDa/domain/place/service/PlaceService.java
Labels: ✨ Feature, 📬 API, 형래

#112 [FIX] 팔로우 Follow API 수정
  src/main/java/com/Udemy/YeoGiDa/domain/follow/controller/FollowController.java
Labels: 🐞 BugFix, 상윤

#114 [FIX] 팔로우 Follow API 수정
  src/main/java/com/Udemy/YeoGiDa/InitDb.java
  src/main/java/com/Udemy/YeoGiDa/domain/comment/repository/CommentRepositoryImpl.java
  src/main/java/com/Udemy/YeoGiDa/domain/follow/controller/FollowController.java
Labels: 🐞 BugFix, 상윤

#116 [FIX] 알람 API 수정
  src/main/java/com/Udemy/YeoGiDa/domain/alarm/response/AlarmListResponseDto.java
  src/main/java/com/Udemy/YeoGiDa/domain/alarm/service/AlarmService.java
Labels: 🐞 BugFix, 형래

#118 [FIX] 팔로우 Follow API 수정
  src/main/java/com/Udemy/YeoGiDa/domain/comment/controller/CommentController.java
  src/main/java/com/Udemy/YeoGiDa/domain/comment/service/CommentService.java
  src/main/java/com/Udemy/YeoGiDa/domain/follow/repository/FollowRepository.java
Labels: 🐞 BugFix, 상윤

#120 [FIX] 팔로우 Follow API 수정
  src/main/java/com/Udemy/YeoGiDa/domain/follow/controller/FollowController.java
  src/main/java/com/Udemy/YeoGiDa/domain/follow/repository/FollowRepository.java
  src/main/java/com/Udemy/YeoGiDa/domain/follow/response/FollowMemberDetailResponseDto.java
  src/main/java/com/Udemy/YeoGiDa/domain/follow/service/FollowService.java
Labels: 🐞 BugFix, 상윤

#122 [CHORE] 배포 서버, DB 재설정
  src/main/java/com/Udemy/YeoGiDa/InitDb.java
  src/main/java/com/Udemy/YeoGiDa/domain/place/response/PlaceListInTripResponseDto.java
  src/main/java/com/Udemy/YeoGiDa/domain/place/service/PlaceService.java
  src/main/resources/application-dev.yml
  src/main/resources/application-prod.yml
  src/test/java/com/Udemy/YeoGiDa/YeoGiDaApplicationTests.java
Labels: ⚙ Setting, 상윤

#124 [FIX] 여행지 API 변경점 수정
  build.gradle
  src/main/java/com/Udemy/YeoGiDa/domain/alarm/entity/Alarm.java
  src/main/java/com/Udemy/YeoGiDa/domain/alarm/repository/AlarmRepositoryCustom.java
  src/main/java/com/Udemy/YeoGiDa/domain/alarm/repository/AlarmRepositoryImpl.java
  src/main/java/com/Udemy/YeoGiDa/domain/alarm/response/AlarmListResponseDto.java
  src/main/java/com/Udemy/YeoGiDa/domain/alarm/service/AlarmService.java
  src/main/java/com/Udemy/YeoGiDa/domain/comment/response/CommentListResponseDto.java
  src/main/java/com/Udemy/YeoGiDa/domain/comment/service/CommentService.java
  src/main/java/com/Udemy/YeoGiDa/domain/follow/controller/FollowController.java
  src/main/java/com/Udemy/YeoGiDa/domain/follow/service/FollowService.java
  src/main/java/com/Udemy/YeoGiDa/domain/heart/repository/HeartRepository.java
  src/main/java/com/Udemy/YeoGiDa/domain/place/repository/PlaceRepository.java
  src/main/java/com/Udemy/YeoGiDa/domain/report/controller/RepositoryController.java
  src/main/java/com/Udemy/YeoGiDa/domain/report/entity/Report.java
  src/main/java/com/Udemy/YeoGiDa/domain/report/repository/ReportRepository.java
  src/main/java/com/Udemy/YeoGiDa/domain/report/request/ReportRequestDto.java
  src/main/java/com/Udemy/YeoGiDa/domain/report/service/ReportService.java
  src/main/java/com/Udemy/YeoGiDa/domain/trip/controller/TripController.java
  src/main/java/com/Udemy/YeoGiDa/domain/trip/response/TripListWithRegionResponseDto.java
  src/main/java/com/Udemy/YeoGiDa/domain/trip/service/TripService.java
  src/main/java/com/Udemy/YeoGiDa/global/slack/dto/SlackMessage.java
  src/main/java/com/Udemy/YeoGiDa/global/slack/service/SlackSender.java
  src/main/resources/application.properties
  src/main/resources/application.yml
Labels: 🐞 BugFix, 📬 API, 형래

#127 [FIX] Mypage 반환값 수정
  src/main/java/com/Udemy/YeoGiDa/domain/follow/service/FollowService.java
  src/main/java/com/Udemy/YeoGiDa/domain/trip/controller/TripController.java
  src/main/java/com/Udemy/YeoGiDa/domain/trip/repository/TripRepositoryCustom.java
  src/main/java/com/Udemy/YeoGiDa/domain/trip/repository/TripRepositoryImpl.java
  src/main/java/com/Udemy/YeoGiDa/domain/trip/service/TripService.java
Labels: 🐞 BugFix, 상윤

#128 [FEAT] 신고 API 와 슬랙 연동
  build.gradle
  src/main/java/com/Udemy/YeoGiDa/domain/comment/service/CommentService.java
  src/main/java/com/Udemy/YeoGiDa/domain/place/response/PlaceAroundMarkerResponseDto.java
  src/main/java/com/Udemy/YeoGiDa/domain/report/controller/ReportController.java
  src/main/java/com/Udemy/YeoGiDa/domain/report/controller/RepositoryController.java
  src/main/java/com/Udemy/YeoGiDa/domain/report/service/ReportService.java
  src/main/java/com/Udemy/YeoGiDa/domain/trip/controller/TripController.java
  src/main/java/com/Udemy/YeoGiDa/domain/trip/response/TripBestListResponseDto.java
  src/main/java/com/Udemy/YeoGiDa/domain/trip/service/TripService.java
  src/main/java/com/Udemy/YeoGiDa/global/slack/dto/SlackMessage.java
  src/main/java/com/Udemy/YeoGiDa/global/slack/service/SlackSender.java
  src/main/java/com/Udemy/YeoGiDa/global/slack/service/SlackService.java
  src/main/resources/application.properties
Labels: ✨ Feature, 📬 API, 형래

#129 [FEAT] 신고 API 와 슬랙 연동
  src/main/java/com/Udemy/YeoGiDa/domain/member/service/MemberService.java
  src/main/java/com/Udemy/YeoGiDa/domain/report/controller/ReportController.java
  src/main/java/com/Udemy/YeoGiDa/domain/report/entity/Report.java
  src/main/java/com/Udemy/YeoGiDa/domain/trip/service/TripService.java
Labels: ✨ Feature, 🐞 BugFix, 📬 API, 형래

#131 [FIX] 좋아요 HeartCount 변경
  src/main/java/com/Udemy/YeoGiDa/domain/heart/repository/HeartRepository.java
  src/main/java/com/Udemy/YeoGiDa/domain/member/service/MemberService.java
  src/main/java/com/Udemy/YeoGiDa/domain/trip/service/TripService.java
  src/main/resources/application-prod.yml
Labels: 🐞 BugFix, 상윤

#132 [FEAT] 신고 API 와 슬랙 연동
  src/main/java/com/Udemy/YeoGiDa/domain/comment/service/CommentService.java
  src/main/java/com/Udemy/YeoGiDa/domain/member/controller/MemberController.java
  src/main/java/com/Udemy/YeoGiDa/domain/member/service/MemberService.java
  src/main/java/com/Udemy/YeoGiDa/domain/report/controller/ReportController.java
  src/main/java/com/Udemy/YeoGiDa/domain/trip/controller/TripController.java
  src/main/java/com/Udemy/YeoGiDa/domain/trip/service/TripService.java
Labels: ✨ Feature, 🐞 BugFix, 📬 API, 형래

#134 [BUG] 회원 이미지 수정 API 버그
  src/main/java/com/Udemy/YeoGiDa/domain/heart/repository/HeartRepository.java
  src/main/java/com/Udemy/YeoGiDa/domain/member/service/MemberService.java
  src/main/java/com/Udemy/YeoGiDa/domain/place/controller/PlaceController.java
  src/main/java/com/Udemy/YeoGiDa/domain/place/service/PlaceService.java
  src/main/java/com/Udemy/YeoGiDa/domain/report/controller/ReportController.java
Labels: 🐞 BugFix, 형래

#138 [BUG] 여행지 좋아요 버그 수정
  src/main/java/com/Udemy/YeoGiDa/domain/alarm/controller/AlarmController.java
  src/main/java/com/Udemy/YeoGiDa/domain/alarm/entity/Alarm.java
  src/main/java/com/Udemy/YeoGiDa/domain/alarm/repository/AlarmRepository.java
  src/main/java/com/Udemy/YeoGiDa/domain/alarm/repository/AlarmRepositoryCustom.java
  src/main/java/com/Udemy/YeoGiDa/domain/alarm/repository/AlarmRepositoryImpl.java
  src/main/java/com/Udemy/YeoGiDa/domain/alarm/response/AlarmListResponseDto.java
  src/main/java/com/Udemy/YeoGiDa/domain/alarm/service/AlarmService.java
  src/main/java/com/Udemy/YeoGiDa/domain/comment/controller/CommentController.java
  src/main/java/com/Udemy/YeoGiDa/domain/comment/service/CommentService.java
  src/main/java/com/Udemy/YeoGiDa/domain/follow/controller/FollowController.java
  src/main/java/com/Udemy/YeoGiDa/domain/follow/service/FollowService.java
  src/main/java/com/Udemy/YeoGiDa/domain/member/controller/MemberController.java
  src/main/java/com/Udemy/YeoGiDa/domain/place/controller/PlaceController.java
  src/main/java/com/Udemy/YeoGiDa/domain/report/controller/ReportController.java
  src/main/java/com/Udemy/YeoGiDa/domain/report/service/ReportService.java
  src/main/java/com/Udemy/YeoGiDa/domain/trip/controller/TripController.java
  src/main/java/com/Udemy/YeoGiDa/domain/trip/service/TripService.java
  src/main/java/com/Udemy/YeoGiDa/global/error/GlobalExceptionHandler.java
  src/main/java/com/Udemy/YeoGiDa/global/fcm/dto/FcmMessage.java
  src/main/java/com/Udemy/YeoGiDa/global/fcm/service/FirebaseCloudMessageService.java
  src/main/java/com/Udemy/YeoGiDa/global/jwt/controller/TokenController.java
  src/main/java/com/Udemy/YeoGiDa/global/jwt/service/JwtProvider.java
  src/main/java/com/Udemy/YeoGiDa/global/response/error/DefaultErrorResult.java
  src/main/java/com/Udemy/YeoGiDa/global/response/error/GlobalExceptionHandler.java
  src/main/java/com/Udemy/YeoGiDa/global/response/success/DefaultResult.java
  src/main/java/com/Udemy/YeoGiDa/global/response/success/ResponseMessage.java
  src/main/java/com/Udemy/YeoGiDa/global/response/success/StatusCode.java
  src/main/java/com/Udemy/YeoGiDa/global/slack/dto/SlackMessage.java
  src/main/java/com/Udemy/YeoGiDa/global/slack/service/SlackSender.java
  src/main/resources/application.properties
Labels: 🐞 BugFix, 형래

#140 [FIX] 내 여행지 좋아요, 내 장소 댓글 알람목록 오는거 수정
  src/main/java/com/Udemy/YeoGiDa/domain/comment/service/CommentService.java
  src/main/java/com/Udemy/YeoGiDa/domain/trip/service/TripService.java
Labels: 🐞 BugFix, 형래

#142 [FIX] 내 여행지 내가한 좋아요 취소 안되던 버그 수정
  src/main/java/com/Udemy/YeoGiDa/domain/trip/service/TripService.java
Labels: 🐞 BugFix, 형래
