Repository YeoGiDa/YeoGiDa-Backend, pull requests merged in 2022-11, with the labels that each got.

#2 [FEAT] 프로젝트 기초세팅
  .gradle/7.5.1/checksums/checksums.lock
  .gradle/7.5.1/dependencies-accessors/dependencies-accessors.lock
  .gradle/7.5.1/dependencies-accessors/gc.properties
  .gradle/7.5.1/executionHistory/executionHistory.lock
  .gradle/7.5.1/fileChanges/last-build.bin
  .gradle/7.5.1/fileHashes/fileHashes.lock
  .gradle/7.5.1/gc.properties
  .gradle/buildOutputCleanup/buildOutputCleanup.lock
  .gradle/buildOutputCleanup/cache.properties
  .gradle/vcs-1/gc.properties
  .idea/.gitignore
  .idea/.name
  .idea/compiler.xml
  .idea/gradle.xml
  .idea/jarRepositories.xml
  .idea/misc.xml
  .idea/vcs.xml
  .idea/workspace.xml
  HELP.md
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/com/Udemy/YeoGiDa/YeoGiDaApplication.java
  src/main/resources/application.properties
  src/test/java/com/Udemy/YeoGiDa/YeoGiDaApplicationTests.java
Labels: documentation, enhancement

#4 [FEAT] Amazon RDS 연결 설정
  .gitignore
  .idea/gradle.xml
  .idea/workspace.xml
  src/main/resources/application.properties
Labels: ⚙ Setting, 형래

#6 [CHORE] Branch test
  .gradle/7.5.1/executionHistory/executionHistory.bin
  .gradle/7.5.1/executionHistory/executionHistory.lock
  .gradle/7.5.1/fileHashes/fileHashes.bin
  .gradle/7.5.1/fileHashes/fileHashes.lock
  .gradle/7.5.1/fileHashes/resourceHashesCache.bin
  .gradle/buildOutputCleanup/buildOutputCleanup.lock
  .gradle/buildOutputCleanup/outputFiles.bin
  .gradle/file-system.probe
  .idea/misc.xml
  .idea/workspace.xml
  build/tmp/compileJava/previous-compilation-data.bin
Labels: ✅ Test, 상윤

#9 [FEAT] 회원 기능 및 카카오 로그인 구현
  .gitignore
  build.gradle
  build/tmp/compileJava/previous-compilation-data.bin
  src/main/java/com/Udemy/YeoGiDa/YeoGiDaApplication.java
  src/main/java/com/Udemy/YeoGiDa/domain/common/entity/BaseEntity.java
  src/main/java/com/Udemy/YeoGiDa/domain/member/controller/MemberController.java
  src/main/java/com/Udemy/YeoGiDa/domain/member/entity/Member.java
  src/main/java/com/Udemy/YeoGiDa/domain/member/exception/AlreadyExistsNicknameException.java
  src/main/java/com/Udemy/YeoGiDa/domain/member/exception/MemberDuplicateException.java
  src/main/java/com/Udemy/YeoGiDa/domain/member/exception/MemberNotFoundException.java
  src/main/java/com/Udemy/YeoGiDa/domain/member/exception/PasswordMismatchException.java
  src/main/java/com/Udemy/YeoGiDa/domain/member/repository/MemberRepository.java
  src/main/java/com/Udemy/YeoGiDa/domain/member/request/MemberJoinRequest.java
  src/main/java/com/Udemy/YeoGiDa/domain/member/request/MemberLoginRequest.java
  src/main/java/com/Udemy/YeoGiDa/domain/member/request/MemberUpdateRequest.java
  src/main/java/com/Udemy/YeoGiDa/domain/member/response/MemberDto.java
  src/main/java/com/Udemy/YeoGiDa/domain/member/response/MemberJoinResponse.java
  src/main/java/com/Udemy/YeoGiDa/domain/member/response/MemberLoginResponse.java
  src/main/java/com/Udemy/YeoGiDa/domain/member/service/MemberService.java
  src/main/java/com/Udemy/YeoGiDa/global/config/EncoderConfig.java
  src/main/java/com/Udemy/YeoGiDa/global/config/JpaAuditingConfig.java
  src/main/java/com/Udemy/YeoGiDa/global/config/QuerydslConfig.java
  src/main/java/com/Udemy/YeoGiDa/global/config/SecurityConfig.java
  src/main/java/com/Udemy/YeoGiDa/global/config/SwaggerConfig.java
  src/main/java/com/Udemy/YeoGiDa/global/error/GlobalExceptionHandler.java
  src/main/java/com/Udemy/YeoGiDa/global/error/dto/ErrorResult.java
  src/main/java/com/Udemy/YeoGiDa/global/exception/ForbiddenException.java
  src/main/java/com/Udemy/YeoGiDa/global/exception/NotFoundException.java
  src/main/java/com/Udemy/YeoGiDa/global/jwt/Token.java
  src/main/java/com/Udemy/YeoGiDa/global/jwt/exception/TokenHasExpiredException.java
  src/main/java/com/Udemy/YeoGiDa/global/jwt/exception/TokenIsInvalidException.java
  src/main/java/com/Udemy/YeoGiDa/global/jwt/filter/JwtAuthenticationFilter.java
  src/main/java/com/Udemy/YeoGiDa/global/jwt/service/JwtProvider.java
  src/main/java/com/Udemy/YeoGiDa/global/response/DefaultResult.java
  src/main/java/com/Udemy/YeoGiDa/global/response/ResponseMessage.java
  src/main/java/com/Udemy/YeoGiDa/global/response/StatusCode.java
  src/main/java/com/Udemy/YeoGiDa/global/security/CustomPrincipalDetailsService.java
  src/main/java/com/Udemy/YeoGiDa/global/security/PrincipalDetails.java
  src/main/java/com/Udemy/YeoGiDa/global/security/annotation/LoginMember.java
  src/main/resources/application.yml
Labels: ✨ Feature, 📬 API, 형래

#10 [FEAT] 여행지 기초 CRUD 기능 개발
  src/main/java/com/Udemy/YeoGiDa/domain/heart/controller/HeartController.java
  src/main/java/com/Udemy/YeoGiDa/domain/heart/entity/Heart.java
  src/main/java/com/Udemy/YeoGiDa/domain/heart/repository/HeartRepository.java
  src/main/java/com/Udemy/YeoGiDa/domain/heart/response/HeartDto.java
  src/main/java/com/Udemy/YeoGiDa/domain/heart/service/HeartService.java
  src/main/java/com/Udemy/YeoGiDa/domain/trip/controller/TripController.java
  src/main/java/com/Udemy/YeoGiDa/domain/trip/entity/Trip.java
  src/main/java/com/Udemy/YeoGiDa/domain/trip/exception/TripNotFoundException.java
  src/main/java/com/Udemy/YeoGiDa/domain/trip/repository/TripRepository.java
  src/main/java/com/Udemy/YeoGiDa/domain/trip/repository/TripRepositoryCustom.java
  src/main/java/com/Udemy/YeoGiDa/domain/trip/repository/TripRepositoryImpl.java
  src/main/java/com/Udemy/YeoGiDa/domain/trip/request/TripSaveRequestDto.java
  src/main/java/com/Udemy/YeoGiDa/domain/trip/response/TripDetailResponseDto.java
  src/main/java/com/Udemy/YeoGiDa/domain/trip/response/TripListResponseDto.java
  src/main/java/com/Udemy/YeoGiDa/domain/trip/service/TripService.java
Labels: ✨ Feature, 📬 API, 형래

#11 [FIX] POST API 서버 인코딩 추가
  src/main/java/com/Udemy/YeoGiDa/domain/member/controller/MemberController.java
Labels: 🐞 BugFix, 📬 API, 형래
