Repository YeoGiDa/YeoGiDa-Backend, pull requests merged in 2023-01, with the labels that each got.

#144 [FIX] Place 장소 장소 목록에서의 여행지 정보 반환값 추가
  src/main/java/com/Udemy/YeoGiDa/domain/place/response/PlaceListInTripResponseDto.java
Labels: 🐞 BugFix, 상윤

#146 [FIX] 알람 목록 조회 response 변경
  src/main/java/com/Udemy/YeoGiDa/domain/alarm/response/AlarmListResponseDto.java
Labels: 🐞 BugFix, 형래

#148 [FEAT] 둘러보기 검색 중심 좌표 반환
  src/main/java/com/Udemy/YeoGiDa/domain/place/controller/PlaceController.java
  src/main/java/com/Udemy/YeoGiDa/domain/place/repository/PlaceRepositoryCustom.java
  src/main/java/com/Udemy/YeoGiDa/domain/place/repository/PlaceRepositoryImpl.java
  src/main/java/com/Udemy/YeoGiDa/domain/place/service/PlaceService.java
  src/main/resources/application.yml
Labels: ✨ Feature, 📬 API, 형래

#151 [FIX] Place 장소 장소 상세에서의 여행지 정보 반환값 추가
  src/main/java/com/Udemy/YeoGiDa/domain/place/response/PlaceDetailResponseDto.java
Labels: 🐞 BugFix, 상윤

#154 [FIX] 장소 Place Request,Response 반환 타입 수정
  src/main/java/com/Udemy/YeoGiDa/domain/place/request/PlaceUpdateRequestDto.java
  src/main/java/com/Udemy/YeoGiDa/domain/place/response/PlaceDetailResponseDto.java
Labels: 🐞 BugFix, 상윤

#155 [FIX] security 설정 변경
  src/main/java/com/Udemy/YeoGiDa/domain/member/controller/MemberController.java
  src/main/java/com/Udemy/YeoGiDa/domain/member/repository/MemberRepository.java
  src/main/java/com/Udemy/YeoGiDa/domain/member/response/MemberLoginResponse.java
  src/main/java/com/Udemy/YeoGiDa/domain/member/service/MemberService.java
  src/main/java/com/Udemy/YeoGiDa/global/config/SecurityConfig.java
  src/main/java/com/Udemy/YeoGiDa/global/jwt/Token.java
  src/main/java/com/Udemy/YeoGiDa/global/jwt/controller/TokenController.java
  src/main/java/com/Udemy/YeoGiDa/global/jwt/dto/TokenInfo.java
  src/main/java/com/Udemy/YeoGiDa/global/jwt/exception/TokenHasExpiredException.java
  src/main/java/com/Udemy/YeoGiDa/global/jwt/filter/JwtAuthenticationFilter.java
  src/main/java/com/Udemy/YeoGiDa/global/jwt/service/JwtProvider.java
  src/main/java/com/Udemy/YeoGiDa/global/jwt/service/JwtTokenProvider.java
  src/main/java/com/Udemy/YeoGiDa/global/response/error/GlobalExceptionHandler.java
  src/main/java/com/Udemy/YeoGiDa/global/security/CustomAuthenticationEntryPoint.java
  src/main/java/com/Udemy/YeoGiDa/global/security/CustomPrincipalDetailsService.java
Labels: ⚙ Setting, 🐞 BugFix, 📬 API, 형래

#157 [FIX] security 설정 변경
  src/main/java/com/Udemy/YeoGiDa/domain/place/entity/Place.java
  src/main/java/com/Udemy/YeoGiDa/domain/place/request/PlaceUpdateRequestDto.java
  src/main/java/com/Udemy/YeoGiDa/domain/place/service/PlaceService.java
  src/main/java/com/Udemy/YeoGiDa/global/config/SecurityConfig.java
  src/main/java/com/Udemy/YeoGiDa/global/jwt/controller/TokenController.java
  src/main/java/com/Udemy/YeoGiDa/global/jwt/service/JwtTokenProvider.java
  src/main/java/com/Udemy/YeoGiDa/global/security/CustomAuthenticationEntryPoint.java
  src/main/resources/application.yml
Labels: 🐞 BugFix, 형래
